apiVersion: v1
kind: Service
metadata:
  labels:
    run: app
  name: app
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    run: app
  sessionAffinity: None
  type: LoadBalancer
