apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      run: db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: db
    spec:
      containers:
      - name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: "123456"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "app"
        image: postgres
        ports:
        - containerPort: 5432



